export const MOVIE_LIST_REQUEST='MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS='MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL='MOVIE_LIST_FAIL'

export const MOVIE_BY_ID_REQUEST='MOVIE_BY_ID_REQUEST'
export const MOVIE_BY_ID_SUCCESS='MOVIE_BY_ID_SUCCESS'
export const MOVIE_BY_ID_FAIL='MOVIE_BY_ID_FAIL'

export const ADD_REVIEW_REQUEST='ADD_REVIEW_REQUEST'
export const ADD_REVIEW_SUCCESS='ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAIL='ADD_REVIEW_FAIL'

export const MOVIE_ADD_REQUEST='MOVIE_ADD_REQUEST'
export const MOVIE_ADD_SUCCESS='MOVIE_ADD_SUCCESS'
export const MOVIE_ADD_FAIL='MOVIE_ADD_FAIL'
export const MOVIE_ADD_RESET='MOVIE_ADD_RESET'


export const MOVIE_DELETE_REQUEST='MOVIE_DELETE_REQUEST'
export const MOVIE_DELETE_SUCCESS='MOVIE_DELETE_SUCCESS'
export const MOVIE_DELETE_FAIL='MOVIE_DELETE_FAIL'