export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS='ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL='SCREEN_LIST_FAIL'
export const ORDER_CREATE_RESET='SCREEN_CREATE_RESET'

export const ORDER_FIND_REQUEST='ORDER_FIND_REQUEST'
export const ORDER_FIND_SUCCESS='ORDER_FIND_SUCCESS'
export const ORDER_FIND_FAIL='SCREEN_FIND_FAIL'

export const ORDER_DELETE_REQUEST='ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS='ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL='SCREEN_DELETE_FAIL'
export const ORDER_DELETE_RESET='SCREEN_DELETE_RESET'


export const ORDER_UPDATE_REQUEST='ORDER_UPDATE_REQUEST'
export const ORDER_UPDATE_SUCCESS='ORDER_UPDATE_SUCCESS'
export const ORDER_UPDATE_FAIL='SCREEN_UPDATE_FAIL'