
export const SCREEN_LIST_REQUEST='SCREEN_LIST_REQUEST'
export const SCREEN_LIST_SUCCESS='SCREEN_LIST_SUCCESS'
export const SCREEN_LIST_FAIL='SCREEN_LIST_FAIL'


export const SCREEN_ADD_REQUEST='SCREEN_ADD_REQUEST'
export const SCREEN_ADD_SUCCESS='SCREEN_ADD_SUCCESS'
export const SCREEN_ADD_FAIL='SCREEN_ADD_FAIL'


export const SCREEN_DELETE_REQUEST='SCREEN_DELETE_REQUEST'
export const SCREEN_DELETE_SUCCESS='SCREEN_DELETE_SUCCESS'
export const SCREEN_DELETE_FAIL='SCREEN_DELETE_FAIL'


